# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(533, 667)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edtOutput = QtWidgets.QLineEdit(MainWindow)
        self.edtOutput.setObjectName("edtOutput")
        self.horizontalLayout.addWidget(self.edtOutput)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.edtClipboard = QtWidgets.QPlainTextEdit(self.groupBox)
        self.edtClipboard.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtClipboard.setReadOnly(True)
        self.edtClipboard.setObjectName("edtClipboard")
        self.verticalLayout_2.addWidget(self.edtClipboard)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(MainWindow)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.edtLog = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.edtLog.setReadOnly(True)
        self.edtLog.setObjectName("edtLog")
        self.verticalLayout.addWidget(self.edtLog)
        self.pbMain = QtWidgets.QProgressBar(self.groupBox_2)
        self.pbMain.setProperty("value", 24)
        self.pbMain.setObjectName("pbMain")
        self.verticalLayout.addWidget(self.pbMain)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnStart = QtWidgets.QToolButton(MainWindow)
        self.btnStart.setMinimumSize(QtCore.QSize(75, 25))
        self.btnStart.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_2.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QToolButton(MainWindow)
        self.btnStop.setMinimumSize(QtCore.QSize(75, 25))
        self.btnStop.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_2.addWidget(self.btnStop)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.label.setText(_translate("MainWindow", "File:"))
        self.groupBox.setTitle(_translate("MainWindow", "Input"))
        self.label_2.setText(_translate("MainWindow", "Clipboard:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Progress"))
        self.btnStart.setText(_translate("MainWindow", "&Start"))
        self.btnStop.setText(_translate("MainWindow", "St&op"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
